### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by RainerHeintzmann** [fiji/View5D#2]
The automatic build seems to fail with this version. I am not sure why though.
Does it have to do with this latest addition of keys?

**Comment by ctrueden** [comment]
Sorry for the delay in reply, @RainerHeintzmann. ~~I'll look into this issue soon, but not before we launch the new ImageJ wiki (in 1 week).~~ Edit: I checked the build log, and the failure is because you cannot deploy the same release version of an artifact to the repository twice. This violates Maven's rule of immutable releases. You need to add `-SNAPSHOT` to the version in your `pom.xml`. To release a version, use the `release-version.sh` script—do not change the version manually to a release version. See https://imagej.net/Releases for details.

In the meantime, I guess @tinevez is uploading the new View5D build to the Java-8 update site for you? Is that satisfactory, for now? Or would you like direct upload rights? (Knowing that in the next few months, the update mechanism for artifacts included with Fiji will change to be Maven-driven...)

If you need help with anything urgently, I warmly invite you to join the fiji/fiji channel on gitter.im, so we can hash things out quickly in real time.

**Comment by ctrueden** [comment]
OK, I apologize, I spoke too soon about the release version. That's not what was going on. I think the deployment credentials are wrong. Investigating now.

**Comment by ctrueden** [comment]
I refreshed the credentials, which I expect will fix the 401 deployment error. But my push hasn't triggered a build (as I notice the last few pushes prior to mine didn't, either). Will try to figure out why not...

**Comment by ctrueden** [comment]
[The build](https://travis-ci.com/github/fiji/View5D/builds/226122561) passed, and [View5D v2.3.6 was released](https://travis-ci.com/github/fiji/View5D/builds/226122549)! It just took Travis CI a while to do it for some reason. But you should be good to go for next time now, @RainerHeintzmann.
